### ISSUE TITLE
An error with installing rstanarm pckage

### ISSUE THREAD

**Issue by Jezahmoud** [tidymodels/tidyposterior#29]
I got the following error with downloading the rstanarm packages

Error: package or namespace load failed for ‘rstanarm’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
namespace ‘Matrix’ 1.2-11 is already loaded, but >= 1.2.13 is required
In addition: Warning message:
package ‘rstanarm’ was built under R version 3.4.4

How to solve this?
Many thanks

**Comment by topepo** [comment]
Can you send your `sessionInfo()`? I'm guessing that this is on 3.4.x. 

Try installing `Matrix` first then `rstanarm` from a fresh R session.

**Comment by Jezahmoud** [comment]
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.3

**Comment by topepo** [comment]
Did the package installs solve the issue?
