### ISSUE TITLE
Unable to install in CentOS7

### ISSUE THREAD

**Issue by leungi** [tidymodels/tidyposterior#33]
Console output below.

Tried installing a few ways, and all give the same error message:

1. from CRAN
2. from RStudio Package Manager Linux binaries
3. from RStudio Package Manager Source

Error message is uninformative, as shown below, so unable to dig deeper.

When `dependencies` is `TRUE`, it fails on `rstanarm` install. Since I've no need for this package , for now, to use with `tidymodels`, hence setting `dependencies=FALSE`, which I'd expected for the install of `tidyposterior` to pass.

Note that `rstan` was installed successfully following its [guide](https://github.com/stan-dev/rstan/wiki/Installing-RStan-on-Linux#c-toolchain-configuration), so previous filed issues don't help in this case.

#### Minimal, runnable code:

```r
> install.packages("tidyposterior", dependencies=FALSE)                                                      
trying URL 'https://cloud.r-project.org/src/contrib/tidyposterior_0.0.2.tar.gz'
Content type 'application/x-gzip' length 60111 bytes (58 KB)
==================================================
downloaded 58 KB

ERROR: dependency ârstanarmâ is not available for package âtidyposteriorâ
* removing â/opt/R/3.6.2/lib/R/library/tidyposteriorâ

The downloaded source packages are in
        â/tmp/RtmpV9MytD/downloaded_packagesâ
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("tidyposterior", dependencies = F) :
  installation of package âtidyposteriorâ had non-zero exit status

```

### Session Info:

```r
> sessioninfo::session_info()
â Session info âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
 setting  value
 version  R version 3.6.2 (2019-12-12)
 os       Red Hat Enterprise Linux Server 7.3 (Maipo)
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Chicago
 date     2020-02-15

â Packages âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
 package     * version date       lib source
 assertthat    0.2.1   2019-03-21 [1] RSPM (R 3.6.1)
 cli           2.0.1   2020-01-08 [1] RSPM (R 3.6.2)
 crayon        1.3.4   2017-09-16 [1] RSPM (R 3.6.2)
 fansi         0.4.1   2020-01-08 [1] RSPM (R 3.6.2)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.2)
 withr         2.1.2   2018-03-15 [1] RSPM (R 3.6.1)

[1] /opt/R/3.6.2/lib/R/library
```

**Comment by topepo** [comment]
There are a lot of issues getting `rstanarm` installed. I would follow up with those maintainers. Once you have that installed, open another issue if installing `tidyposterior` is a problem.

**Comment by leungi** [comment]
Noted; thanks @topepo .

**Comment by leungi** [comment]
Thanks to @HenrikBengtsson, and with reference to stan-dev/rstanarm#420.

`tidymodels` installed successfully with `rstanarm` install.
